# Generated by Django 3.0.3 on 2020-04-08 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='job_place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='place')),
                ('job', models.CharField(max_length=100, verbose_name='job description')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comments')),
            ],
        ),
        migrations.CreateModel(
            name='job_user_allotment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allotment.job_place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
